name: Build and deploy compiler explorer
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Use OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.12.x

      - run: opam install dune ppx_yojson_conv js_of_ocaml js_of_ocaml-ppx

      - name: Build the js-of-ocaml lib
        run: opam exec -- dune build web/export.bc.js

      - name: Install and Build 🔧
        working-directory: ./compiler-explorer
        run: |
          yarn install
          yarn build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: compiler-explorer/build # The folder the action should deploy.
